version: '3.2'

services:
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

  django:
    build:
      context: shortUrlService/
    ports:
      - "8000:8000"
    networks:
      - shorturlservice
  angular:
    build:
      context: short-url-ui/
    ports:
      - "4200:4200"
    networks:
      - shorturlservice

networks:
  shorturlservice:
    driver: bridge

